

platform :ios, '13.4'
use_modular_headers!


linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym

  # Aquí añades la línea para usar Firebase como un marco estático
  $RNFirebaseAsStaticFramework = true
end

def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

target 'Besseri' do

  # Aquí insertas la línea requerida justo antes de `use_react_native!`
  # require Pod::Executable.execute_command('node', ['-p',
  #   'require.resolve(
  #     "react-native/scripts/react_native_pods.rb",
  #     {paths: [process.argv[1]]},
  #   )', __dir__]).strip
  node_require('react-native/scripts/react_native_pods.rb')
  node_require('react-native-permissions/scripts/setup.rb')




  setup_permissions([
  'LocationWhenInUse',
  'LocationAlways',
  ])

    pod 'GoogleUtilities', :modular_headers => true
    pod 'TOCropViewController', '~> 2.3.0'
    # # Otras dependencias
    # pod 'Firebase/Core'
    pod 'FirebaseCoreInternal', :modular_headers => true

  config = use_native_modules!


  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :fabric_enabled => true
  )

  target 'BesseriTests' do
    inherit! :complete
    # Pods for testing
  end



  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
